#1[
#1 TITULO: COMENTÁRIO
#1 AUTOR: AFONSO CELSO ROCHA MASTRELLI
#1 DATA: 29/06/1988
#1 VERSAO: 1.2
#1 FINALIDADE: GERAR RELATÓRIO CONTENDO A DOCUMENTAÇÃO DE DETERMINADO PROGRAMA
#1 ENTRADAS: ARQUIVO QUE CONTEM O CÓDIGO FONTE (EM PASCAL, COBOL OU ZIM) COMENTADO POR NÍVEIS; CÓDIGO DO NÍVEL DE COMENTÁRIO DESEJADO;
#1 SAIDAS: RELATÓRIO COM A DOCUMENTAÇÃO EXTRAÍDA DO ARQUIVO FONTE;
#1 ROTINAS CHAMADAS: LIB$DO_COMMAND (EXTERNA), MOSTRA_TELA, CABEÇALHO, RELA_RELATPAS E SYS$ASCTIM (EXTERNA);
#1]

#1[
#1 ROTINA: MOSTRA_TELA
#1 FINALIDADE: MOSTRA MENU AO USUÁRIO, PERGUNTANDO E RECEBENDO O NÍVEL DE DOCUMENTAÇÃO QUE ELE QUER E O NOME DO ARQUIVO A SER LIDO, PASSANDO ESSAS INFORMAÇÕES AO PROGRAMA PRINCIPAL
#1 ENTRADAS: NÍVEL DE DOCUMENTAÇÃO E NOME DO ARQUIVO A SER LIDO
#1 DEPENDENCIAS: NÍVEL DE DOCUMENTAÇÃO E NOME DO ARQUIVO A SER LIDO
#1 CHAMADO POR: COMENTARIO
#1 CHAMA: COMENTARIO
#1]

#2[
#2 PSEUDOCODIGO DE: MOSTRA_TELA
#2 LIMPA A TELA 
#2 MOSTRA MENU DE OPÇÕES AO USUARIO
#2 LE OPÇÃO DO USUÁRIO
#2 OPCAO LIDA E DE CONTINAUR EXECUCAO?
#2      LE NOME DO ARQUIVO DE ENTRADA
#2      LE NOME DA LINGUAGEM UTILIZADA NO PROGRAMA
#2      LINGUAGEM NÃO É COBOL NEM ZIM?
#2              ASSUME-SE PASCAL COMO LINGUAGEM UTILIZADA   
#2]

#3[
#3 DETALHES DE: MOSTRA_TELA
#3 LIMPA TELA FOI PRODUZIDA USANDO WRITE(CLS), PORQUE, DADO QUE CLS ESTÁ VAZIO, O BUFFER É ALTERADO PARA UMA STRING VAZIA
#3 AS OPÇÕES DO MENU ESTÃO NO ARQUIVO constants.py, EM FORMATO DE LISTA
#3 CASO SEJA FORNECIDO A ENTRADA DEVMODE SERÃO CRIADOS ARQUIVOS .JSON COM O PRODUTO CARTESIANO DOS NÍVEIS DISPONÍVEIS  
#3]