'''
 1 
 TITULO: COMENTÁRIO
 AUTOR: AFONSO CELSO ROCHA MASTRELLI
 DATA: 29/06/1988
 VERSAO: 1.2
 FINALIDADE: GERAR RELATÓRIO CONTENDO A DOCUMENTAÇÃO DE DETERMINADO PROGRAMA
 ENTRADAS: ARQUIVO QUE CONTEM O CÓDIGO FONTE (EM PASCAL, COBOL OU ZIM) COMENTADO POR NÍVEIS; CÓDIGO DO NÍVEL DE COMENTÁRIO DESEJADO;
 SAÍDAS: RELATÓRIO COM A DOCUMENTAÇÃO EXTRAÍDA DO ARQUIVO FONTE;
 ROTINAS CHAMADAS: LIB$DO_COMMAND (EXTERNA), MOSTRA_TELA, CABEÇALHO, RELA_RELATPAS E SYS$ASCTIM (EXTERNA); 
 1
'''
'''
 1
 ROTINA: MOSTRA_TELA
 FINALIDADE: MOSTRA MENU AO USUÁRIO, PERGUNTANDO E RECEBENDO O NÍVEL DE DOCUMENTAÇÃO QUE ELE QUER E O NOME DO ARQUIVO A SER LIDO, PASSANDO ESSAS INFORMAÇÕES AO PROGRAMA PRINCIPAL
 ENTRADAS: NÍVEL DE DOCUMENTAÇÃO E NOME DO ARQUIVO A SER LIDO
 EXPORTAÇÕES GLOBAIS: NÍVEL DE DOCUMENTAÇÃO E NOME DO ARQUIVO A SER LIDO
 CHAMADO POR: COMENTARIO
 1
'''
'''
 2
 PSEUDOCODIGO_DE: MOSTRA_TELA
 LIMPA A TELA 
 MOSTRA MENU DE OPÇÕES AO USUARIO
 LE OPÇÃO DO USUÁRIO
 OPCAO LIDA E DE CONTINAUR EXECUCAO?
      LE NOME DO ARQUIVO DE ENTRADA
      LE NOME DA LINGUAGEM UTILIZADA NO PROGRAMA
      LINGUAGEM NÃO É COBOL NEM ZIM?
              ASSUME-SE PASCAL COMO LINGUAGEM UTILIZADA
 2
'''
'''
 3
 DETALHES_DE: MOSTRA_TELA
 LIMPA TELA FOI PRODUZIDA USANDO WRITE(CLS), PORQUE, DADO QUE CLS ESTÁ VAZIO, O BUFFER É ALTERADO PARA UMA STRING VAZIA
 AS OPÇÕES DO MENU ESTÃO NO ARQUIVO constants.py, EM FORMATO DE LISTA
 CASO SEJA FORNECIDO A ENTRADA DEVMODE SERÃO CRIADOS ARQUIVOS .JSON COM O PRODUTO CARTESIANO DOS NÍVEIS DISPONÍVEIS
 3
'''



